# BlueMap : config coeur (copiée dans plugins/BlueMap/core.conf au premier démarrage)
# accept-download: true = acceptation de l'EULA Mojang, BlueMap télécharge le client MC pour les textures.
accept-download: true

data: "bluemap"

# Serveur N100 3 vCPU : 1 thread de rendu pour ne pas pénaliser le jeu.
render-thread-count: 1
render-thread-priority: 1

update-cooldown: 60
full-update-interval: 1440
region-file-check-interval: 5
scan-for-mod-resources: true
metrics: false

log: {
  file: "bluemap/logs/debug.log"
  append: false
}
